In [1]:
import pandas as pd
df = pd.read_csv('student_data.csv')
df.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10

In [2]:
print(f"5: {df.shape[0]} | 33: {df.shape[1]}\n")

df.info()

5: 395 | 33: 33

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 395 entries, 0 to 394
Data columns (total 33 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   school      395 non-null    object
 1   sex         395 non-null    object
 2   age         395 non-null    int64
 3   address     395 non-null    object
 4   famsize     395 non-null    object
 5   Pstatus     395 non-null    object
 6   Medu        395 non-null    int64
 7   Fedu        395 non-null    int64
 8   Mjob        395 non-null    object
 9   Fjob        395 non-null    object
 10  reason      395 non-null    object
 11  guardian    395 non-null    object
 12  traveltime  395 non-null    int64
 13  studytime   395 non-null    int64
 14  failures    395 non-null    int64
 15  schoolsup   395 non-null    object
 16  famsup      395 non-null    object
 17  paid        395 non-null    object
 18  activities  395 non-null    object
 19  nursery     395 non-null    object
 20  higher      395 non-null    object
 21  internet    395 non-null    object
 22  romantic    395 non-null    object
 23  famrel      395 non-null    int64
 24  freetime    395 non-null    int64
 25  goout       395 non-null    int64
 26  Dalc        395 non-null    int64
 27  Walc        395 non-null    int64
 28  health      395 non-null    int64
 29  absences    395 non-null    int64
 30  G1          395 non-null    int64
 31  G2          395 non-null    int64
 32  G3          395 non-null    int64
dtypes: int64(16), object(17)
memory usage: 102.0+ KB

In [3]:
df.isnull().sum()

school        0
sex           0
age           0
address       0
famsize       0
Pstatus       0
Medu          0
Fedu          0
Mjob          0
Fjob          0
reason        0
guardian      0
traveltime    0
studytime     0
failures      0
schoolsup     0
famsup        0
paid          0
activities    0
nursery       0
higher        0
internet      0
romantic      0
famrel        0
freetime      0
goout         0
Dalc          0
Walc          0
health        0
absences      0
G1            0
G2            0
G3            0
dtype: int64

In [4]:
import pandas as pd


missing_data = pd.DataFrame({
    'عدد القيم المفقودة': df.isnull().sum(),
    'النسبة المئوية (%)': (df.isnull().sum() / len(df)) * 100
})

missing_data = missing_data.sort_values(by='عدد القيم المفقودة', ascending=False)

display(missing_data)

            عدد القيم المفقودة  النسبة المئوية (%)
school                       0                 0.0
sex                          0                 0.0
age                          0                 0.0
address                      0                 0.0
famsize                      0                 0.0
Pstatus                      0                 0.0
Medu                         0                 0.0
Fedu                         0                 0.0
Mjob                         0                 0.0
Fjob                         0                 0.0
reason                       0                 0.0
guardian                     0                 0.0
traveltime                   0                 0.0
studytime                    0                 0.0
failures                     0                 0.0
schoolsup                    0                 0.0
famsup                       0                 0.0
paid                         0                 0.0
activities                   0                 0.0
nursery                      0                 0.0
higher                       0                 0.0
internet                     0                 0.0
romantic                     0                 0.0
famrel                       0                 0.0
freetime                     0                 0.0
goout                        0                 0.0
Dalc                         0                 0.0
Walc                         0                 0.0
health                       0                 0.0
absences                     0                 0.0
G1                           0                 0.0
G2                           0                 0.0
G3                           0                 0.0

In [5]:
import pandas as pd
desc_stats = df.describe().T
display(desc_stats)

            count       mean       std   min   25%   50%   75%   max
age         395.0  16.696203  1.276043  15.0  16.0  17.0  18.0  22.0
Medu        395.0   2.749367  1.094735   0.0   2.0   3.0   4.0   4.0
Fedu        395.0   2.521519  1.088201   0.0   2.0   2.0   3.0   4.0
traveltime  395.0   1.448101  0.697505   1.0   1.0   1.0   2.0   4.0
studytime   395.0   2.035443  0.839240   1.0   1.0   2.0   2.0   4.0
failures    395.0   0.334177  0.743651   0.0   0.0   0.0   0.0   3.0
famrel      395.0   3.944304  0.896659   1.0   4.0   4.0   5.0   5.0
freetime    395.0   3.235443  0.998862   1.0   3.0   3.0   4.0   5.0
goout       395.0   3.108861  1.113278   1.0   2.0   3.0   4.0   5.0
Dalc        395.0   1.481013  0.890741   1.0   1.0   1.0   2.0   5.0
Walc        395.0   2.291139  1.287897   1.0   1.0   2.0   3.0   5.0
health      395.0   3.554430  1.390303   1.0   3.0   4.0   5.0   5.0
absences    395.0   5.708861  8.003096   0.0   0.0   4.0   8.0  75.0
G1          395.0  10.908861  3.319195   3.0   8.0  11.0  13.0  19.0
G2          395.0  10.713924  3.761505   0.0   9.0  11.0  13.0  19.0
G3          395.0  10.415190  4.581443   0.0   8.0  11.0  14.0  20.0

In [6]:
numeric_cols = df.select_dtypes(include=['number'])
skew_values = numeric_cols.skew()
print(skew_values)

age           0.466270
Medu         -0.318381
Fedu         -0.031672
traveltime    1.607029
studytime     0.632142
failures      2.387026
famrel       -0.951882
freetime     -0.163351
goout         0.116502
Dalc          2.190762
Walc          0.611960
health       -0.494604
absences      3.671579
G1            0.240613
G2           -0.431645
G3           -0.732672
dtype: float64

In [7]:
categorical_cols = df.select_dtypes(include=['object'])
print(categorical_cols.head())
print(df['sex'].value_counts())

  school sex address famsize Pstatus     Mjob      Fjob  reason guardian  \
0     GP   F       U     GT3       A  at_home   teacher  course   mother
1     GP   F       U     GT3       T  at_home     other  course   father
2     GP   F       U     LE3       T  at_home     other   other   mother
3     GP   F       U     GT3       T   health  services    home   mother
4     GP   F       U     GT3       T    other     other    home   father

  schoolsup famsup paid activities nursery higher internet romantic
0       yes     no   no         no     yes    yes       no       no
1        no    yes   no         no      no    yes      yes       no
2       yes     no  yes         no     yes    yes      yes       no
3        no    yes  yes        yes     yes    yes      yes      yes
4        no    yes  yes         no     yes    yes       no       no
sex
F    208
M    187
Name: count, dtype: int64

In [8]:
skewness = df.select_dtypes(include=['number']).skew().to_frame(name='Skewness')
display(skewness)

            Skewness
age         0.466270
Medu       -0.318381
Fedu       -0.031672
traveltime  1.607029
studytime   0.632142
failures    2.387026
famrel     -0.951882
freetime   -0.163351
goout       0.116502
Dalc        2.190762
Walc        0.611960
health     -0.494604
absences    3.671579
G1          0.240613
G2         -0.431645
G3         -0.732672

In [9]:
df.describe(include=['O']).T

           count unique     top freq
school       395      2      GP  349
sex          395      2       F  208
address      395      2       U  307
famsize      395      2     GT3  281
Pstatus      395      2       T  354
Mjob         395      5   other  141
Fjob         395      5   other  217
reason       395      4  course  145
guardian     395      3  mother  273
schoolsup    395      2      no  344
famsup       395      2     yes  242
paid         395      2      no  214
activities   395      2     yes  201
nursery      395      2     yes  314
higher       395      2     yes  375
internet     395      2     yes  329
romantic     395      2      no  263

In [5]:
import os
print(os.listdir('.'))

['.ipynb_checkpoints', '.ipython', '.jupyter', '.local', '.m2', '.openjfx', '.packettracer', '.scenebuilder', '.templateengine', '.vscode', '.vscode-shared', 'AppData', 'Application Data', 'bacman25.py', 'bacman25.spec', 'Bengaluru_House_Data.csv', 'build', 'Cisco Packet Tracer 9.0.1', 'Contacts', 'Cookies', 'dist', 'Documents', 'Downloads', 'Favorites', 'Group1_Descriptive_Analysis.ipynb', 'IdeaProjects', 'IntelGraphicsProfiles', 'kc_house_data.csv', 'kc_house_data.csv.zip', 'Links', 'Local Settings', 'Music', 'My Documents', 'NetHood', 'NTUSER.DAT', 'ntuser.dat.LOG1', 'ntuser.dat.LOG2', 'NTUSER.DAT{fe606ede-dda5-11f0-85b8-f8e4e3fed665}.TM.blf', 'NTUSER.DAT{fe606ede-dda5-11f0-85b8-f8e4e3fed665}.TMContainer00000000000000000001.regtrans-ms', 'NTUSER.DAT{fe606ede-dda5-11f0-85b8-f8e4e3fed665}.TMContainer00000000000000000002.regtrans-ms', 'ntuser.ini', 'OneDrive', 'PrintHood', 'Recent', 'Saved Games', 'Searches', 'SendTo', 'Social_media_impact_on_life.csv', 'source', 'Start Menu', 'student_data.csv', 'Templates', 'Untitled-1.py', 'Untitled.ipynb', 'Untitled1.ipynb', 'Untitled10.ipynb', 'Untitled11.ipynb', 'Untitled2.ipynb', 'Untitled3.ipynb', 'Untitled4.ipynb', 'Untitled5.ipynb', 'Untitled6.ipynb', 'Untitled7.ipynb', 'Untitled8.ipynb', 'Untitled9.ipynb', 'Videos', 'WPS Cloud Files']

In [7]:
import pandas as pd

df = pd.read_csv('student_data.csv')
desc_stats = df.describe().T
desc_stats.to_excel('Group1_Final_Report.xlsx')

print("تم إنشاء وحفظ ملف الإكسل بنجاح!")

تم إنشاء وحفظ ملف الإكسل بنجاح!